#!/usr/bin/perl
use strict;
use warnings;
use lib 'lib', "$ENV{HOME}/hck/opensource-trunk/Class-Persist/lib";
use HTTP::Daemon;
use Net::DAAP::Server;

my $path = shift || 't/lib/';

my $server = Net::DAAP::Server->new(path => $path);
my $d = HTTP::Daemon->new(
    LocalAddr => 'localhost',
    LocalPort => 3689,
    ReuseAddr => 1) || die;

print "Please contact me at: ", $d->url, "\n";
while (my $c = $d->accept) {
    while (my $request = $c->get_request) {
        my $response = $server->run($request);
        $c->send_response ($response);
    }
    $c->close;
    undef($c);
}

